### ISSUE TITLE
localhost:27017: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by jepunband** [flipkart-incubator/RTA#8]
hi getting this error:

$sudo python rta.py --url "vulnweb.com" -v -s

fTraceback (most recent call last):
  File "rta.py", line 416, in <module>
    main()
  File "rta.py", line 389, in main
    recon = Recon()
  File "rta.py", line 55, in __init__
    self.scraper = scraper.Scraper()
  File "/home/apps/gits/RTA/recon/scraper/scraper.py", line 37, in __init__
    self.collection.create_index([("url", DESCENDING), ("hostname", ASCENDING)], unique=True)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 1387, in create_index
    self.__create_index(keys, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 1294, in __create_index
    with self._socket_for_writes() as sock_info:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 762, in _get_socket
    server = self._get_topology().select_server(selector)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 210, in select_server
    address))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 186, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused

**Comment by a0xnirudh** [comment]
@jepunband This is happening because the mongo service is not running (as mentioned in the error: `localhost:27017: [Errno 111] Connection refused`. Please try to connect to mongo service from command line and make sure the service is up and running before running RTA.
